### ISSUE TITLE
Coordination for minimal path/encryption/whatever

### ISSUE THREAD

**Issue by zeebo** [storj/storj#2289]
# STUFF TO DO

- [x] Minimal encryption store integration (#2293)
- [x] Password based key derivation (#2294)
- [ ] libuplink Share type (#2296)
- [ ] ~Uplink setup changes~
- [ ] Encryption context changes (#2302)

<sup>(checked when complete)</sup>

## Minimal encryption store integration

- [x] Claimed

Take the knowledge gained from jw/path-abstraction and do the bare minimum to integrate an `encryption.Store` into the code base so that it can handle keys rooted anywhere.

Some things to worry about:

- Macaroons that restrict from accessing bucket metadata
- Encryption with the store matches the current stuff
- Any bugs that got fixed/uncovered in jw/path-abstraction

## Password based key derivation

- [x] Claimed

In [this design doc](https://github.com/storj/storj/blob/3d6b25a043bc7850da130cc0f78dd2fabda8dfcf/docs/design/password-key-derivation.md), two algorithms are described:

- One to derive a rootKey
- One to derive a defaultPassword

The encryption package should export two functions with signatures

```go
func DeriveRootKey(password string, salt []byte, path storj.Path) (*storj.Key, error) {}

func DeriveDefaultPassword(password string, salt []byte) (string, error) {}
```

The `DeriveDefaultPassword` should `baseN` encode the output for whatever `N` we typically use. The calls to `argon2i` in the design document should actually be `argon2id` and we should use [this method](https://godoc.org/golang.org/x/crypto/argon2#IDKey) from the `x/crypto` libraries.

Unclear what to do about parameter choice.

## libuplink Share type

- [X] Claimed

libuplink should export a type `Share` with the following interface

```go
type Share struct {
    SatelliteURL     string
    APIKey           APIKey
    EncryptionAccess EncryptionAccess
}

func ParseShare(data []byte) (*Share, error) {}

func (s *Share) Serialize() []byte {}
```

<sup>types may differ. serialize should match the name `APIKey` uses.</sup>

Additionally, the `EncryptionAccess` struct should gain an `UnencryptedPath` field. The `Share` `Serialize` method should probably be `baseN` encoded for whatever `N` we typically use.

## Uplink setup changes

- [x] Claimed

The `uplink setup` command needs to change to be able to be set up with a share. The config files also need to be able to handle a share, probably with some backwards compatibility concerns.

Not really too sure what to do here because I'm really bad at user facing things. At the end of the day, though, one just needs to pass the appropriate values into libuplink.
