### ISSUE TITLE
Create test suite for testing Storjscan

### ISSUE THREAD

**Issue by shaupt131** [storj/storj#4860]
Originally part of https://github.com/storj/storj/issues/4823, but broken out into a separate issue.  

Test plan: https://github.com/storj/storj/pull/4672

**Storj Scan**

- [x]  Minimum Confirmation (from test plan document)
- [x] Backfilling the USD value of transactions - If storjscan goes down or can't connect to the 3rd party API we are using to determine the price of the token at the time of the transaction we need to ensure that when things go back to normal this data is automagically backfilled. 
- [ ] Backfilling transactions that were missed - If we cant query transactions from the ETH node when storjscan is able to reconnect the satellite is able to retrieve all missing payments (https://github.com/storj/storjscan/issues/59)
- [ ]  Verify that STORJ payments that occur while the invoices are being generated behave as expected (double-counting payments, taking credit for pending payments, adding invoice items for pending invoice items) (https://github.com/storj/storjscan/issues/60)
- [ ] **TBD (go through test plan and determine if we need any other test cases.  Add them to the list here**

**Not Storjscan specific but we should still implement:**

- [ ]  Do not allow for user balances on the satellite to go negative (https://github.com/storj/storj/issues/5092)
- [ ]  **TBD (go through test plan and determine if we need any other test cases. Add them to the list here**

**Acceptance Criteria:** 

- Add additional test cases to this ticket as needed based on review of test plan
- Determine what test framework to use
- Create initial test suite
   - Work will be broken up into smaller chunks and assigned.

**Comment by iglesiasbrandon** [comment]
PR: https://review.dev.storj.io/c/storj/storj/+/7935
