### ISSUE TITLE
Test Invite Project Member

### ISSUE THREAD

**Issue by littleskunk** [storj/storj#6007]
https://github.com/storj/storj/blob/main/docs/testplan/invite-project-member-testplan.md

- [x] Member can't edit projects details
- [x] invite a person that doesn't exist in the database. -> Signup process
- [x] invite a person that hasn't finished the signup process (email confirmation outstanding)
- [x] URL encoding https://satellite.qa.storj.io/login?email=jens+1@storj.io
- [x] privilages of owner vs member (at the moment owner can invite others = bug)
- [x] Feedback for the owner for existing and not existing accounts. The owner should not be able to see the difference.
- [x] Can this be used to send spam mails?
- [x] Can this be used to send malicious mails? See https://github.com/storj/storj-private/issues/222
- [x] Limits for the email address. Not more than 72 chars.
- [ ] SQL Injection? Maybe test with burb suite or similar.

Create bugs for
- [x] Spam mails https://github.com/storj/storj-private/issues/355
- [x] Invite customer that hasn't finished signup process https://github.com/storj/storj/issues/6033
- [x] Privileges for members (will get implemented later)
- [x] Resend invite https://github.com/storj/storj/issues/6031
- [x] Error message on invite duplicates (has been fixed)
- [x] Invite members twice by adding spaces at the end https://github.com/storj/storj/issues/6030
- [x] Remove member from the list (has been fixed)

**Comment by littleskunk** [comment]
Create bugs for
* Spam mails
* Invite customer that hasn't finished signup process
* Privileges for members
* Resend invite
* Error message on invite duplicates
* Invite members twice by adding spaces at the end

**Comment by littleskunk** [comment]
Currently we don't have the skillset to run tests with burb suite. I would say out of scope for the moment and hopefully one day we will find the time for a udemy training.
