### ISSUE TITLE
Vuetify app: account settings page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6083]
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6088
- [ ] https://github.com/storj/storj/issues/6089
- [ ] https://github.com/storj/storj/issues/6090
- [ ] https://github.com/storj/storj/issues/6091
```

**Comment by jewharton** [comment]
Closing because all tasks in the list have been completed.
