### ISSUE TITLE
Vuetify app: billing page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6084]
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6095
- [ ] https://github.com/storj/storj/issues/6096
- [ ] https://github.com/storj/storj/issues/6097
- [ ] https://github.com/storj/storj/issues/6098
- [ ] https://github.com/storj/storj/issues/6099
- [ ] https://github.com/storj/storj/issues/6117
```
