### ISSUE TITLE
Vuetify app: object browser

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6085]
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6101
- [ ] https://github.com/storj/storj/issues/6102
- [ ] https://github.com/storj/storj/issues/6104
- [ ] https://github.com/storj/storj/issues/6105
- [ ] https://github.com/storj/storj/issues/6106
- [ ] https://github.com/storj/storj/issues/6107
- [ ] https://github.com/storj/storj/issues/6108
- [ ] https://github.com/storj/storj/issues/6100
- [ ] https://github.com/storj/storj/issues/6110
- [ ] https://github.com/storj/storj/issues/6111
- [ ] https://github.com/storj/storj/issues/6199
- [ ] https://github.com/storj/storj/issues/6257
```
