### ISSUE TITLE
Vuetify: buckets page

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6086]
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6062
- [ ] https://github.com/storj/storj/issues/6112
- [ ] https://github.com/storj/storj/issues/6113
- [ ] https://github.com/storj/storj/issues/6114
- [ ] https://github.com/storj/storj/issues/6115
- [ ] https://github.com/storj/storj/issues/6116
```

**Comment by jewharton** [comment]
Closing because all tasks in the list have been completed.
