### ISSUE TITLE
Remove GraphQL dependency

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6131]
Goal: Replace all graphql handlers with our more standard http endpoint style, so that we can completely remove the GraphQL dependency from the frontend and the backend

For each endpoint in the tasklist:
* create corresponding http handler in `web/satellite/console/consoleweb/consoleapi` to accomplish the equivalent behavior of the GQL endpoint
* switch the frontend to use the new http endpoint rather than the graphql handler
* don't worry about removing the GraphQL backend handling until all endpoints are migrated

Final steps:
* Once all endpoints are migrated, remove all GraphQL-related code (and dependencies that are no longer needed) from `web/satellite`
* Completely remove `satellite/console/consleweb/consoleql` and any other no-longer-necessary GraphQL code on the backend

```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6132
- [ ] https://github.com/storj/storj/issues/6134
- [ ] https://github.com/storj/storj/issues/6133
- [ ] https://github.com/storj/storj/issues/6135
- [ ] https://github.com/storj/storj/issues/6136
- [ ] https://github.com/storj/storj/issues/6137
- [ ] https://github.com/storj/storj/issues/6138
- [ ] https://github.com/storj/storj/issues/6139
- [ ] https://github.com/storj/storj/issues/6140
- [ ] https://github.com/storj/storj/issues/6141
- [ ] https://github.com/storj/storj/issues/6142
- [ ] https://github.com/storj/storj/issues/6195
```
