### ISSUE TITLE
Better Visibility Into Status of Users Accounts

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6244]
### Describe the feature or problem you'd like to solve

 - We want to be able to easily see the status of a users account in a single place:
   - Examples that are hard to see today are permanently suspended accounts as well as accounts that are subject to billing freeze
 - We expected to see this in the `status` column of the `users` table

### Propose a Solution

 - Thinking that we add new options to the status column in the users table so that can be the source of truth for the customers status

### Open Discussion
- Given that "permanent suspension" involves simply reducing limits, we might need to change how this works, considering that's not a great trigger to add a status of "permanently suspended" to the users table

### AC:
write proposal on how to make account statuses easily visible. including; billing freeze and permanent freeze. 
post document in slack to get feedback/approval from key stakeholders
make tickets with the steps required to implement the solution based on comments in slack
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6302
- [ ] https://github.com/storj/storj-private/issues/386
- [ ] https://github.com/storj/storj/issues/6303
- [ ] https://github.com/storj/storj/issues/6410
- [ ] https://github.com/storj/storj/issues/6304
- [ ] https://github.com/storj/storj/issues/6438
```

**Comment by boshevski** [comment]
I added designs for account status visibility and changing status in the admin ui.

**Comment by ferristocrat** [comment]
> I added designs for account status visibility and changing status in the admin ui.

Added the link and screenshot to the description above

**Comment by ferristocrat** [comment]
@mobyvb / @wilfred-asomanii / @NiaStorj   - Is this complete?

**Comment by mobyvb** [comment]
this is complete now
