### ISSUE TITLE
Object TTL per access grant / S3 credentials

### ISSUE THREAD

**Issue by kaloyan-raev** [storj/storj#6249]
**Describe the feature or problem you'd like to solve**

Some customers want to upload files through the S3 gateway with an automatic expiration time. Their S3 app does not provide the option to send custom HTTP headers, so they cannot use the existing [Object-level TTL feature](https://github.com/storj/gateway-st/blob/main/docs/s3-compatibility.md#object-level-ttl).

**Propose a Solution**

Add an optional `MaxObjectTTL` permission to the access grant caveats. If an object is uploaded with such an access grant, an expiration time shall be set to reflect the configured `MaxObjectTTL` period. For example, if the `MaxObjectTTL` period is set to 30 days, the expiration time shall be set to 30 days after the time the object upload was initiated.

If the `MaxObjectTTL` permission is not set, there shall be no change in behavior.

The users would set the new `MaxObjectTTL` permission using the `uplink access restrict` CLI command. Then, they would also need to call `uplink access register` to register the restricted access grant as S3 credentials.

**Corner Cases**
- If multiple caveats in the macaroon chain set the `MaxObjectTTL` permission, the shortest period is the effective TTL.
- In case an object is uploaded with explicit an Object-level TTL and an access grant with `MaxObjectTTL`
  - If the Object-level TTL is shorter than the `MaxObjectTTL`, the Object-level TTL will be the effective TTL.
  - If the Object-level TTL is longer than the `MaxObjectTTL`, the upload will fail with an error.

**Out of Scope**
- Exposing the new `MaxObjectTTL` permission in the Satellite GUI is out of scope. For now, it will be available only in the Uplink CLI.

**Additional context**

- The `MaxObjectTTL` permission in the access grants builds on the existing object expiration time feature. As such, it suffers from the same limitation. Once set, the expiration time of an object cannot be changed without re-uploading the object.
- The user can use a new access grant or S3 credentials with a different `MaxObjectTTL` permission, but it will apply only to newly uploaded objects.
- If a different Object TTL is required for different object key prefixes, the user can configure a separate pair of S3 credentials for each of the prefixes.
```[tasklist]
### Tasks
- [x] Implement `Duration` in picobuf
- [x] Add `MaxObjectTTL` permission to the APIKey macaroon caveats
- [x] Modify the satellite's `BeginObject` endpoint to respect the `MaxObjectTTL` permission
- [x] Add `--max-object-ttl` flag to the `uplink access restrict` CLI command
- [x] Add user documentation to https://docs.storj.io/dcs/buckets/object-lifecycles
```

**Comment by kaloyan-raev** [comment]
Deployed to production.
