### ISSUE TITLE
Vuetify gaps (tasklist)

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6263]
This issue tracks Vuetify POC tasks that were not captured by our initial tickets. Almost all functionality has been implemented, but there are some areas we missed

If you want to work on one of these tasks, and it is not yet an issue:
* create issue from tasklist item
  * if you want, you can combine multiple tasklist items into one issue - just make sure to remove the duplicate tasklist items afterwards
* add to Integrations Team project
* apply "vuetify" label to task and assign yourself
* add an Effort estimation, or otherwise apply the "needs estimation" label and post in the poker planner channel
* if you are starting the task, set "Status"=in progress, and "Sprint"=current sprint

```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6278
- [ ] https://github.com/storj/storj/issues/6288
- [ ] https://github.com/storj/storj/issues/6279
- [ ] https://github.com/storj/storj/issues/6280
- [ ] https://github.com/storj/storj/issues/6281
- [ ] https://github.com/storj/storj/issues/6282
- [ ] https://github.com/storj/storj/issues/6283
- [ ] https://github.com/storj/storj/issues/6284
- [ ] https://github.com/storj/storj/issues/6299
- [ ] https://github.com/storj/storj/issues/6266
- [ ] https://github.com/storj/storj/issues/6300
- [ ] https://github.com/storj/storj/issues/6267
- [ ] https://github.com/storj/storj/issues/6308
- [ ] https://github.com/storj/storj/issues/6334
- [ ] https://github.com/storj/storj/issues/6305
- [ ] https://github.com/storj/storj/issues/6309
- [ ] https://github.com/storj/storj/issues/6310
- [ ] https://github.com/storj/storj/issues/6311
- [ ] https://github.com/storj/storj/issues/6292
- [ ] https://github.com/storj/storj/issues/6335
- [ ] https://github.com/storj/storj/issues/6293
- [ ] https://github.com/storj/storj/issues/6294
- [ ] https://github.com/storj/storj/issues/6319
- [ ] https://github.com/storj/storj/issues/6295
- [ ] https://github.com/storj/storj/issues/6312
- [ ] https://github.com/storj/storj/issues/6397
- [ ] https://github.com/storj/storj/issues/6306
- [ ] https://github.com/storj/storj/issues/6307
- [ ] https://github.com/storj/storj/issues/6321
- [x] Vuetify: add segment count to buckets table
- [ ] https://github.com/storj/storj/issues/6322
- [ ] https://github.com/storj/storj/issues/6327
- [ ] https://github.com/storj/storj/issues/6320
- [ ] https://github.com/storj/storj/issues/6298
- [x] Vuetify: add favicon
- [ ] https://github.com/storj/storj/issues/6331
- [ ] https://github.com/storj/storj/issues/6332
- [ ] https://github.com/storj/storj/issues/6315
- [ ] https://github.com/storj/storj/issues/6342
- [ ] https://github.com/storj/storj/issues/6343
- [ ] https://github.com/storj/storj/issues/6364
- [x] Vuetify: Visible error when navigating to Billing -> STORJ Transactions and no wallet exists
- [ ] https://github.com/storj/storj/issues/6411
- [ ] https://github.com/storj/storj/issues/6400
- [ ] https://github.com/storj/storj/issues/6433
```
