### ISSUE TITLE
Update timing of freeze emails

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6314]
### Objective
Reducing the time between non-payment and date at which account is subject to deletion

## Acceptance Criteria
Timing is updated to the following:
![image](https://github.com/storj/storj/assets/7063002/ecec0668-3cc9-40de-9834-4b840e803707)
Figma: https://www.figma.com/file/ghA8757OzO0M5Fi4T0WMT5/Delinquent-Account-Suspension-and-Deletion-Flow?type=whiteboard&node-id=1-5319&t=NiiYBq3b8KBiTYgg-0

This can be easily done in the Hubspot workflows for freeze ([production](https://app.hubspot.com/workflows/20293085/platform/flow/407260204/edit), [qa](https://app.hubspot.com/workflows/20293085/platform/flow/401996404/edit))

Notes:

1. create new updated timeline hubspot flow (don't introduce users to it yet)
2. add int for number of days until next step to freeze table - populate existing rows with the current default. Insert the current default for new rows.
3. default value can be updated as part of the same change, or a commit on top
4. around the same time the new satellite version is deployed, turn on the updated timeline hubspot flow, and remove the start triggers from the old flows, without ejecting anyone from that flow

```[tasklist]
### Tasks
- [x] Update flow diagram and add here
- [ ] Verify timing between invoice and first email
- [ ] Get approval from Dorrie
- [ ] Update HubSpot timing and emails
- [ ] Update configuration for timing
- [ ] Start thinking of how we can migrate off HubSpot emails and onto something like SES
- [ ] https://github.com/storj/storj/issues/6382
```

**Comment by ferristocrat** [comment]
@iglesiasbrandon - Can you double check the timing in Stripe? I think we reduced the timing to not retry at all, right?
