### ISSUE TITLE
Vuetify gaps 2

### ISSUE THREAD

**Issue by NiaStorj** [storj/storj#6377]
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6412
- [ ] https://github.com/storj/storj/issues/6394
- [ ] https://github.com/storj/storj/issues/6393
- [ ] https://github.com/storj/storj/issues/6399
- [ ] https://github.com/storj/storj/issues/6395
- [ ] https://github.com/storj/storj/issues/6424
- [ ] https://github.com/storj/storj/issues/6425
```

**Comment by iglesiasbrandon** [comment]
this issue is done/deployed. i am going to close it.
