### ISSUE TITLE
Vuetify: final tasks/polishing before turning on in production

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6535]
This tasklist tracks high-priority Vuetify tasks that need to be completed before we are comfortable turning on the Vuetify app under the /v2/ prefix on in production. There may still be other issues present outside this list, but this list is the minimal tasks that need to be done.
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6536
- [ ] https://github.com/storj/storj/issues/6546
- [ ] https://github.com/storj/storj/issues/6547
- [ ] https://github.com/storj/storj/issues/6552
```
