### ISSUE TITLE
Create satellite release

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6578]
```[tasklist]
### Tasks
- [x] cut release branch
- [x] create binaries for darwin
- [x] post changelog in storj forum for discussion
- [x] check config changes (and for new contributors)
- [x] check new signup flow on V2
- [x] check invoice aggregation/idempotency
- [x] check input limit restrictions in v2 app
- [x] check partner signup/onboarding for v2 app
```
