### ISSUE TITLE
Vuetify Bugs and Feature Gaps

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6628]
### Summary

Will create a tasklist of V2 bugs, and we can convert the ones that are required for complete production switch into issues.

```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6631
- [ ] https://github.com/storj/storj/issues/6632
- [ ] https://github.com/storj/storj/issues/6630
- [ ] https://github.com/storj/storj/issues/6633
- [ ] https://github.com/storj/storj/issues/6634
- [ ] https://github.com/storj/storj/issues/6636
- [ ] https://github.com/storj/storj/issues/6637
- [ ] https://github.com/storj/storj/issues/6638
- [ ] https://github.com/storj/storj/issues/6639
- [ ] https://github.com/storj/storj/issues/6735
```
