### ISSUE TITLE
Test Veeam Against Various Satellite/Region Combinations

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6677]
**Describe the feature or problem you'd like to solve**

We want to see if satellite/region is a factor in Veeam performance.

**Propose a Solution**

- Test the following combinations in the Veeam Chicago environment:
  - US Satellite - US1 Select Bucket
  - US1 Satellite - US1 Geofence Bucket
  - US1 Satellite - Public Bucket
- Trace the 95th percentile vs 75th percentile events, using Jaeger or Grafana

```[tasklist]
### Tasks
- [ ] US Satellite - US1 Select Bucket
- [ ] US1 Satellite - US1 Geofence Bucket
- [ ] US1 Satellite - Public Bucket
- [ ] Create trace graph to analyze
- [ ] Analyze traces and summarize any findings
```

**Additional context**

**Comment by derek-storj** [comment]
**Veeam Direct Backup to Storj Select Bucket**
- 1MB Veeam Block Size
- Bucket Name: veeam
- AK: juxggebwtx6kpxcgjljuja4isgoa
- Backup of 8.5GB VM
- Job start: 1/9/2024 13:28:38 Eastern
- Job finish: 1/9/2024 13:36:53 Eastern
- Veeam's Calculated Processing Rate: 59MB/s

**Comment by derek-storj** [comment]
**Veeam Direct Backup to Storj US-Geofenced Bucket**

- 1MB Veeam Block Size
- Bucket Name: veeam-usaonly
- AK: jx3uk3m7dvafouepqegesmip5vta
- Backup of 8.5GB VM
- Job start: 1/9/2024 13:05:14 Eastern
- Job finish: 1/9/2024 13:17:54 Eastern
- Veeam's Caclucalted Processing Rate: 28MB/s

**Comment by derek-storj** [comment]
**Veeam Direct Backup to Storj Public**

- 1MB Veeam Block Size
- Bucket Name: veeam
- AK: jvaqjxrcu5nmtkympqsvfmae6iwq
- Backup of 8.5GB VM
- Job start: 1/9/2024 13:18:03 Eastern
- Job finish: 1/9/2024 13:27:37 Eastern
- Veeam's Caclucalted Processing Rate: 46MB/s
