### ISSUE TITLE
Turn on v2 for all

### ISSUE THREAD

**Issue by ferristocrat** [storj/storj#6687]
Use this as a parent to hold any issues for things we need to do before we can toggle on v2 as the default.
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6681
- [ ] https://github.com/storj/storj-private/issues/545
- [ ] https://github.com/storj/storj/issues/6699
- [ ] https://github.com/storj/storj/issues/6688
```
