### ISSUE TITLE
Completing V2: cleanup

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6689]
Once the V2 app is turned on in production by default, we will want to clean up the old app quickly afterwards. This ticket tracks the remaining tasks to accomplish that.
```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6722
- [ ] https://github.com/storj/storj/issues/6723
- [ ] https://github.com/storj/storj/issues/6724
```
