### ISSUE TITLE
Improve code coverage in satellite/console

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6755]
This ticket is designed to be completed in one sprint by the Console team. Individual items on the checklist do not need to be converted to issues, and can simply be checked when merged.

**Instructions for working on tasks:**

If you want to "claim" a checklist item, please edit the issue and put your username beside it, so that no one else tries to work on the same thing.

_If the function is an unused feature, remove it_. Otherwise, add testing to it. After merging your changes, check the item in the list.

**Instructions for generating coverage report:**
1. run `go test -coverprofile cover.out ./satellite/console/...` 
2. `go tool cover -html=cover.out` to view an html version of the report

**Tasks for this body of work:**
- [ ] `SetupAccount()` in `console/service.go` and `consoleapi/auth.go`
- [ ] `GetUsageReport()` in `console/service.go`
- [ ] `GetProjectUsage()` in `console/service.go`
- [ ] `GetBucketTotals()` in `console/service.go`
- [ ] `UpdateAccount()` in `console/service.go` and `consoleapi/auth.go`
- [ ] `AttemptPayOverdueInvoices()` in `console/service.go`
- [ ] `DeleteAccount()` in `console/service.go`
- [ ] `BillingHistory()` in `console/service.go` and `consoleapi/payments.go`
- [ ] `InvoiceHistory()` in `console/service.go` and `consoleapi/payments.go`

This is not an exhaustive list - do not add new items to it.

**Comment by wilfred-asomanii** [comment]
Looks like there's a test, `TestPayOverdueInvoices` in `invoices_test.go` that tests `AttemptPayOverdueInvoices`
See https://github.com/storj/storj/blob/fd835859d58c375d631e3ee6590a9f3a54e2cf71/satellite/payments/stripe/invoices_test.go#L80

**Comment by mobyvb** [comment]
@wilfred-asomanii thanks for finding that
maybe for payments/stripe-related wrapper functions, we can skip them if there is an adequate test in the stripe package. In this case I think it's okay because the only thing consoleService.AttemptPayOverdueInvoices does is call stripeService.AttemptPayOverdueInvoices. No additional logic is introduced, besides the audit log that happens in every console service function.

**Comment by egonelbre** [comment]
To get the latest coverage report it's also possible to see it in Jenkins https://build.dev.storj.tools/job/storj/job/main/cobertura.

Also note that `go test -coverprofile cover.out ./satellite/console/...` may miss some of the coverage, because sometimes some other packages also cover code in `satellite/console` -- though, I'm not sure how common it is for `satellite/console`. For example, many things in `satellite/satellitedb` are tested from other packages.

**Comment by mobyvb** [comment]
@egonelbre @wilfred-asomanii already noticed that with one of the tests he looked into - `AttemptPayOverdueInvoices` is not tested in the console package, but it is tested in the payments package

**Comment by VitaliiShpital** [comment]
`GetProjectUsage() in console/service.go`
and
 `GetBucketTotals() in console/service.go`

use methods which are very well tested in satellite/accounting/projectusage_test.go

**Comment by egonelbre** [comment]
Ok, I managed to recently get one run https://build.dev.storj.tools/job/storj/job/main/4139/cobertura/

**Comment by mobyvb** [comment]
@egonelbre do you know if there is a way to view coverage of the line-by-line code from the report you shared? I'm only able to see high-level info, like what percentage of specific files are covered. I haven't figured out how to view the file itself to see which lines are covered

**Comment by egonelbre** [comment]
@mobyvb, unfortunately that one no. I think I tried at some point using something, but the sizes were quite large for that. 

Maybe we can just persist the coverage as an artifact, and then people can open them up locally somehow. Not sure whether we need to fix some paths, but should be doable.

**Comment by egonelbre** [comment]
I created https://review.dev.storj.io/c/storj/storj/+/12527 for now. There also seem to be Jenkins plugins that can show more detailed information https://plugins.jenkins.io/coverage, but currently that install failed.

**Comment by egonelbre** [comment]
The builds now contain the compressed coverage profile https://build.dev.storj.tools/blue/organizations/jenkins/storj/detail/main/4157/artifacts/

**Comment by NiaStorj** [comment]
12/19/24:

This ticket is stale. We should create smaller tickets for the remaining tasks. @mobyvb
