### ISSUE TITLE
Satellite-Managed Encryption Passphrases

### ISSUE THREAD

**Issue by mobyvb** [storj/storj#6912]
Design doc: https://github.com/storj/design-docs/blob/main/20240129-satellite-managed-encryption.md

```[tasklist]
### Tasks
- [ ] https://github.com/storj/storj/issues/6913
- [ ] https://github.com/storj/storj/issues/6914
- [ ] https://github.com/storj/storj/issues/6915
- [ ] https://github.com/storj/storj/issues/6923
- [ ] Enable satellite-managed encryption passphrase with secure credentials in QA
- [ ] Ensure that satellite api fails to start up if incorrect "master encryption passphase" is loaded
- [ ] https://github.com/storj/storj/issues/6980
- [ ] https://github.com/storj/storj/issues/6993
- [ ] https://github.com/storj/storj/issues/6994
- [ ] https://github.com/storj/storj/issues/6995
- [ ] https://github.com/storj/storj/issues/7020
- [ ] https://github.com/storj/storj/issues/7049
- [ ] https://github.com/storj/storj/issues/7071
```

**Comment by mobyvb** [comment]
Deployed on March 20, 2025
